version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 99
  labels:
  - dependencies
  ignore:
  - dependency-name: node
    versions:
    - ">= 15.a, < 16"
  - dependency-name: node
    versions:
    - 14.15.5.pre.alpine3.12
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 99
  labels:
  - dependencies
  versioning-strategy: increase
  ignore:
  - dependency-name: semantic-release
    versions:
    - 17.4.0
    - 17.4.1
